CREATE TABLE IF NOT EXISTS AU_FOLDER
(
	ID BIGINT NOT NULL IDENTITY,
    NAME VARCHAR(200) NOT NULL,
	INSERT_DATE TIMESTAMP NOT NULL,
	VERSION BIGINT,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS AU_TAG
(
    ID BIGINT NOT NULL IDENTITY,
    NAME VARCHAR(200) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS AU_THUMBNAIL
(
    ID BIGINT NOT NULL IDENTITY,
    THUMBNAIL VARBINARY NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS AU_PICTURE_DATA
(
    ID BIGINT NOT NULL IDENTITY,
    DATA VARBINARY NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS AU_PICTURE
(
    ID BIGINT NOT NULL IDENTITY,
    DATE_INSERT TIMESTAMP NOT NULL,
    QUALITY VARCHAR(200) NOT NULL,
    PICTURE_NAME VARCHAR(200) NOT NULL,
    DATA_ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    FOLDER_ID BIGINT NOT NULL,
    THUMBNAIL_ID BIGINT NOT NULL,
    VERSION BIGINT,
    FOREIGN KEY (FOLDER_ID) REFERENCES AU_FOLDER (ID),
    FOREIGN KEY (THUMBNAIL_ID) REFERENCES AU_THUMBNAIL (ID),
    FOREIGN KEY (DATA_ID) REFERENCES AU_PICTURE_DATA (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS AU_PICTURE_TAG
(
    PICTURE_ID   BIGINT,
    TAG_ID       BIGINT,
    PRIMARY KEY (PICTURE_ID, TAG_ID),
    FOREIGN KEY (PICTURE_ID) REFERENCES AU_PICTURE (ID),
    FOREIGN KEY (TAG_ID) REFERENCES AU_TAG (ID)
);

CREATE SEQUENCE hibernate_sequence